
"""Add fingerprint to alarms

Revision ID: 007
Revises: 006
Create Date: 2025-06-29 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarms', sa.Column('fingerprint', sa.String(length=255), nullable=True, comment='Unique fingerprint for deduplication'))
    op.create_index(op.f('ix_alarms_fingerprint'), 'alarms', ['fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alarms_fingerprint'), table_name='alarms')
    op.drop_column('alarms', 'fingerprint')
    # ### end Alembic commands ###
