
"""Add subject_template and html_template to notification_templates

Revision ID: 008
Revises: 007
Create Date: 2025-06-29 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008'
down_revision = '007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_templates', sa.Column('subject_template', sa.Text(), nullable=True))
    op.add_column('notification_templates', sa.Column('html_template', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_templates', 'html_template')
    op.drop_column('notification_templates', 'subject_template')
    # ### end Alembic commands ###
